---
{{ $dsSimWebPort := 8090 }}
{{ $dsSimWebPath := "/" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "ds-sim.fullname" .}}-web
  labels:
    {{- include "ds-sim.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ include "ds-sim.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "ds-sim.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          image: {{ include "ds-sim-web.image" . }}
          imagePullPolicy: {{ include "ds-sim.pullPolicy" . }}
          volumeMounts:
           - name: config
             mountPath: /home/simulator/config/application.yml
             subPath: application.yml
          readinessProbe:
            httpGet:
              path: /
              port: {{ $dsSimWebPort }}
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{include "ds-sim.fullname" .}}-web-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ds-sim.labels" . | nindent 4 }}
  name: {{ .Values.serviceSettings.name }}-web
spec:
  externalName: {{ .Values.serviceSettings.name }}
  ports:
  - name: server
    protocol: TCP
    port: {{ $dsSimWebPort }}
    targetPort: {{ $dsSimWebPort }}
    {{- if eq .Values.env.type "dev"  }}
    nodePort: 32004
    {{- end }}
  - name: discover
    protocol: TCP
    port: 4840
    targetPort: 4840
    {{- if eq .Values.env.type "dev"  }}
    nodePort: 32005
    {{- end }}
  - name: opcau
    protocol: TCP
    port: 5005
    targetPort: 5005
    {{- if eq .Values.env.type "dev"  }}
    nodePort: 32006
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "ds-sim.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ include "ds-sim.serviceType" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{include "ds-sim.fullname" .}}-web
  labels:
    {{- include "ds-sim.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ .Release.Namespace }}/webds/(.*)
        backend:
          service:
            name: {{ .Values.serviceSettings.name }}-web
            port:
              name: server
        pathType: ImplementationSpecific
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "ds-sim.fullname" .}}-web-config
data:
  application.yml: |-
    server:
      port: {{ $dsSimWebPort }}
    logging:
      config: ./config/logback-spring.xml
    opcUa:
      server:
        tcp:
          port: 4840
      clientIP:
        EGUI: 192.168.1.1
        LMC: 192.168.1.2

